import { Product } from "@/types/product";

export const products: Product[] = [
    {
        id: "1",
        name: "Pastel de Nata Cake",
        nameKey: "pastelDeNata",
        description: "A giant, creamy interpretation of Lisbon's most famous pastry. Crispy puff pastry layers with custard cream.",
        price: 35.00,
        category: "Celebration",
        flavor: "Vanilla & Cinnamon",
        image: "https://images.unsplash.com/photo-1590080874088-eec64895b423?auto=format&fit=crop&q=80&w=800",
        rating: 4.9,
        reviews: 128,
        allergens: ["Eggs", "Dairy", "Gluten"],
    },
    {
        id: "2",
        name: "Sintra Forest",
        nameKey: "sintraForest",
        description: "Dark chocolate sponge with cherry compote and whipped cream, inspired by the misty forests of Sintra.",
        price: 42.00,
        category: "Celebration",
        flavor: "Chocolate & Cherry",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800",
        rating: 4.8,
        reviews: 85,
        allergens: ["Eggs", "Dairy", "Gluten"],
    },
    {
        id: "3",
        name: "Algarve Almond",
        nameKey: "algarveAlmond",
        description: "Traditional almond cake made with locally sourced almonds and a hint of orange zest.",
        price: 28.00,
        category: "Everyday",
        flavor: "Almond & Orange",
        image: "https://images.unsplash.com/photo-1514517604298-cf80e0fb7f1e?auto=format&fit=crop&q=80&w=800",
        rating: 4.7,
        reviews: 64,
        allergens: ["Nuts", "Eggs"],
    },
    {
        id: "4",
        name: "Lemon & Basil Breeze",
        nameKey: "lemonBasil",
        description: "Light lemon sponge with a basil-infused buttercream. Refreshing and unique.",
        price: 38.00,
        category: "Seasonal",
        flavor: "Lemon & Basil",
        image: "https://images.unsplash.com/photo-1519340333755-96605553e1d9?auto=format&fit=crop&q=80&w=800",
        rating: 4.6,
        reviews: 42,
        allergens: ["Eggs", "Dairy", "Gluten"],
    },
    {
        id: "5",
        name: "Royal Red Velvet",
        nameKey: "royalRedVelvet",
        description: "Velvety sponge with cream cheese frosting and edible gold leaf.",
        price: 45.00,
        category: "Wedding",
        flavor: "Red Velvet",
        image: "https://images.unsplash.com/photo-1586788680434-30d324671b6c?auto=format&fit=crop&q=80&w=800",
        rating: 5.0,
        reviews: 32,
        allergens: ["Eggs", "Dairy", "Gluten"],
    },
    {
        id: "6",
        name: "Port Wine Drunkard",
        nameKey: "portWine",
        description: "Rich chocolate cake soaked in fine Port wine, topped with ganache.",
        price: 40.00,
        category: "Celebration",
        flavor: "Chocolate & Port Wine",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800",
        rating: 4.9,
        reviews: 95,
        allergens: ["Eggs", "Dairy", "Gluten", "Alcohol"],
    },
];
